version: '3'

services:
  proxy:
    image: yano3/nginx-ngx_mruby:latest
    volumes:
      - ./proxy/proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '10080:80'
  app1:
    image: php:apache
    volumes:
      - ./app1:/var/www/html
  app2:
    image: php:apache
    volumes:
      - ./app2:/var/www/html
